# Generated by Django 3.0 on 2021-04-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='listfebric',
            old_name='c_name',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='listfebric',
            old_name='p_name',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='p_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parent'),
        ),
    ]
