# Generated by Django 3.0 on 2021-04-27 17:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_multistepformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfebric',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
